---
- include: ../../common/tasks/mesosphere_apt.yml
- name: Install mesos
  apt:
    state: present
    name: mesos

- name: Stop Zookeeper and Mesos
  service:
    state: stopped
    name: '{{ item }}'
  with_items:
    - zookeeper
    - mesos-master

- name: Zookeeper override
  template:
    src: zookeeper.override
    dest: /etc/init/zookeeper.override
  notify:
    - restart mesos-slave

- name: Mesos zk
  template:
    src: ../../mesos-master/templates/zk_mesos
    dest: /etc/mesos/zk
  notify:
    - restart mesos-slave

- name: Mesos master override
  template:
    src: mesos-master.override
    dest: /etc/init/mesos-master.override
  notify:
    - restart mesos-slave

- name: Mesos IP
  template:
    src: ../../mesos-master/templates/ip
    dest: /etc/mesos-slave/ip
  notify:
    - restart mesos-slave

- name: Mesos Hostname
  template:
    src: ../../mesos-master/templates/hostname
    dest: /etc/mesos-slave/hostname
  notify:
    - restart mesos-slave
